### RigUI Script generated by Bone Manager Addon ###

import bpy

from bpy.utils import register_class, unregister_class

BM_rig_id = "BM_40co00t3nmb6"


class BM_PT_rigui_BM_40co00t3nmb6(bpy.types.Panel):
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_category = 'Item'
	bl_label = "Rig UI"
	bl_idname = "BM_PT_rigui_BM_40co00t3nmb6"


	@classmethod
	def poll(self, context):
		try:
			return (context.active_object.data.get("BM_rig_id") == BM_rig_id)
		except (AttributeError, KeyError, TypeError):
			return False

	def draw(self, context):
		arm = context.active_object.data
		bcolls = arm.collections_all
		layout = self.layout
		layout = layout.column()
		row = layout.row(align=True)

		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Root"], "is_visible", toggle=True, text="Root")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Root"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)
		row.separator(factor=1.5)
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Skull"], "is_visible", toggle=True, text="Skull")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Skull"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Spine"], "is_visible", toggle=True, text="Spine")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Spine"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Shoulders"], "is_visible", toggle=True, text="Shoulders")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Shoulders"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)
		row.separator(factor=1.5)
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Left Arm Ik"], "is_visible", toggle=True, text="IK Arm L")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Left Arm Ik"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Right Arm Ik"], "is_visible", toggle=True, text="IK Arm R")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Right Arm Ik"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["FK-Left Arm"], "is_visible", toggle=True, text="FK Arm L")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "FK-Left Arm"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["FK-Right Arm"], "is_visible", toggle=True, text="FK Arm R")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "FK-Right Arm"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Left Hand"], "is_visible", toggle=True, text="Left Hand")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Left Hand"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Fingers"], "is_visible", toggle=True, text="Fingers")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Fingers"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Right Hand"], "is_visible", toggle=True, text="Right Hand")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Right Hand"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)
		row.separator(factor=1.5)
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Left Leg IK"], "is_visible", toggle=True, text="IK Leg L")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Left Leg IK"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Right Leg IK"], "is_visible", toggle=True, text="IK Leg R")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Right Leg IK"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["FK-Left Leg"], "is_visible", toggle=True, text="FK Leg L")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "FK-Left Leg"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["FK-Right Leg"], "is_visible", toggle=True, text="FK Leg R")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "FK-Right Leg"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Left Foot"], "is_visible", toggle=True, text="Left Foot")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Left Foot"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Toes"], "is_visible", toggle=True, text="Toes")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Toes"
		op.arm_name = context.active_object.name
		slot.separator(factor=2)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Right Foot"], "is_visible", toggle=True, text="Right Foot")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Right Foot"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)
		row.separator(factor=1.5)
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["Bulk Bone Manipulation"], "is_visible", toggle=True, text="Bulk Bone Manipulation")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "Bulk Bone Manipulation"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["MECH"], "is_visible", toggle=True, text="MECH")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "MECH"
		op.arm_name = context.active_object.name

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["DEF - Skeleton"], "is_visible", toggle=True, text="Deformation Bones")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "DEF - Skeleton"
		op.arm_name = context.active_object.name
		row = layout.row(align=True)

		slot = row.row(align=True)
		button = slot.row(align=True)
		button.prop(bcolls["CTRL_Placement"], "is_visible", toggle=True, text="CTRL_Placement")
		picker = slot.row(align=True)
		picker.scale_x = 0.9
		op = picker.operator("bonemanex.collection_select", text="", icon="RESTRICT_SELECT_OFF")
		op.bcoll_name = "CTRL_Placement"
		op.arm_name = context.active_object.name


class BM_PT_dynamicPanel_BM_40co00t3nmb6(bpy.types.Panel):
	bl_category = 'Item'
	bl_label = "Dynamic Panel"
	bl_idname = "BM_PT_dynamicPanelBM_40co00t3nmb6"
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_options = {'DEFAULT_CLOSED'}

	@classmethod
	def poll(self, context):
		try:
			return (context.active_object.data.get("BM_rig_id") == BM_rig_id)
		except (AttributeError, KeyError, TypeError):
			return False

	def draw(self, context):
		layout = self.layout

		header, panel = layout.panel('Rig Settings', default_closed=False)
		header.label(text='Rig Settings')
		if panel:
			box = panel.box()
			row= box.row(align=True)
			row.label(text = 'Left Arm IK - FK')
			row.prop(bpy.data.objects['Male_Skeleton-rig'].pose.bones['Rig Settings'], '["Left Arm IK - FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Left Leg IK - FK')
			row.prop(bpy.data.objects['Male_Skeleton-rig'].pose.bones['Rig Settings'], '["Left Leg IK - FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Right Arm IK - FK')
			row.prop(bpy.data.objects['Male_Skeleton-rig'].pose.bones['Rig Settings'], '["Right Arm IK - FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Right Leg IK - FK')
			row.prop(bpy.data.objects['Male_Skeleton-rig'].pose.bones['Rig Settings'], '["Right Leg IK - FK"]', text = '', emboss=True, toggle=True, slider=True)

			row= box.row(align=True)
			row.label(text = 'Bone Thickness')
			row.prop(bpy.data.objects['Male_Skeleton-rig'].pose.bones['Rig Settings'], '["Bone Thickness"]', text = '', emboss=True, toggle=True, slider=True)



class BM_PT_customprops_BM_40co00t3nmb6(bpy.types.Panel):
	bl_category = 'Item'
	bl_label = "Rig Properties"
	bl_idname = "BM_PT_customprops_BM_40co00t3nmb6"
	bl_space_type = 'VIEW_3D'
	bl_region_type = 'UI'
	bl_options = {'DEFAULT_CLOSED'}

	@classmethod
	def poll(self, context):
		if context.active_object.data.get('BM_rig_id'):
			pose_bones = context.selected_pose_bones
			props = None
			rna_properties = {prop.identifier for prop in bpy.types.PoseBone.bl_rna.properties if prop.is_runtime}
			if context.selected_pose_bones:
				bones = context.selected_pose_bones

			elif context.mode == 'OBJECT':
				bones = context.active_object.pose.bones

			else:
				return False
			if bones:
				props = [[prop for prop in bone.items() if prop not in rna_properties] for bone in bones]

			if props and bones:
				return (context.active_object.data.get("BM_rig_id") == BM_rig_id)
			else:
				return False

		else:
			return False

	def draw(self, context):
		layout = self.layout
		pose_bones = context.active_object.pose.bones
		if context.selected_pose_bones:
			bones = context.selected_pose_bones

		elif context.selected_editable_bones:
			bones = [pose_bones[bone.name] for bone in context.selected_editable_bones]

		else:
			bones = context.active_object.pose.bones

		def assign_props(row, val, key):
			row.property = key
			row.data_path = "active_pose_bone"
			try:
				row.value = str(val)
			except:
				pass

		rna_properties = {
			prop.identifier for prop in bpy.types.PoseBone.bl_rna.properties
			if prop.is_runtime
		}

		skip_keys = rna_properties

	# Iterate through selected bones add each prop property of each bone to the panel.
		if context.selected_pose_bones is not None:
			for bone in context.selected_pose_bones:
				for i, key in enumerate(sorted(bone.keys())):
					if key not in skip_keys:
						if i == 0:
							box = layout.box()
						val = bone.get(key, "value")
						row = box.row()
						split = row.split(align=True, factor=0.7)
						row = split.row(align=True)
						row.label(text=key, translate=False)
						row = split.row(align=True)
						row.prop(bone, f'["{key}"]', text = "", slider=True)


def get_bones(ob, context, collection, selected):
	arm = ob.data
	if collection:
		bones = arm.collections_all[collection.name].bones
		if selected:
			try:
				if bpy.app.version < (5, 0, 0):
					bones = [bone for bone in bones if bone.select is True]
				else:
					bones = [bone for bone in ob.pose.bones if bone.select is True]
			except TypeError:
				return []
	elif selected and not collection:
		try:
			if bpy.app.version < (5, 0, 0):
				bones = [bone for bone in bones if bone.select is True]
			else:
				bones = [bone for bone in ob.pose.bones if bone.select is True]
		except TypeError:
			return []
	else:
		bones = ob,pose.bones
	return bones


class BMEX_OT_selectCollection(bpy.types.Operator):
	bl_idname = "bonemanex.collection_select"
	bl_label = ""
	bl_description = "Select all Bones in Collection.\nShift to add to selection. \nAlt to remove from selection"

	bcoll_name : bpy.props.StringProperty(name="Collection name", description="Name of bone collection", default="",)
	arm_name : bpy.props.StringProperty(name="Armature name", description="Name of armature", default="",)

	@classmethod
	def poll(self, context):

		return context.mode == "POSE"

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.shift = False
		self.alt = False

	def invoke(self, context, event):
		self.shift = event.shift
		self.alt = event.alt

		return self.execute(context)

	def execute(self, context):
		ob = context.active_object
		arm = ob.data
		bcolls = arm.collections_all
		bcoll = arm.collections_all[self.bcoll_name]

		if self.alt:
			bones = get_bones(ob, context, bcoll, True)
			for bone in bones:
				if bpy.app.version < (5, 0, 0):
					bone.select = False
					bone.select_head = False
					bone.select_tail = False

				else:
					ob.pose.bones[bone.name].select = False

		else:
			bones = get_bones(ob, context, bcoll, False)
			if not self.shift:
				bpy.ops.pose.select_all(action="DESELECT")

			for bone in bones:
				if bpy.app.version < (5, 0, 0):
					bone.select = True
					bone.select_head = True
					bone.select_tail = True

				else:
					ob.pose.bones[bone.name].select = True

		return {"FINISHED"}


classes = (BM_PT_rigui_BM_40co00t3nmb6,BMEX_OT_selectCollection, BM_PT_customprops_BM_40co00t3nmb6, BM_PT_dynamicPanel_BM_40co00t3nmb6, BMEX_OT_selectCollection)

def register():
	for cls in classes:
		try:
			register_class(cls)

		except ValueError:
			pass
def unregister():
	for cls in classes:
		try:
			unregister_class(cls)

		except ValueError:
			pass


if __name__ == "__main__":
	register()